[tool.poetry]
name = "my-algorithm-project"
version = "0.1.0"
description = ""
authors = ["thomasthaddeus <thaddeus.r.thomas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
